server:
    port: 9090
spring:
    profiles:
        active: dev
    output: 
        ansi: 
            enabled: ALWAYS
    datasource:
        url: jdbc:mysql://127.0.0.1/platform
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            # 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 180000
            # 连接池最大连接数，默认是10
            maximum-pool-size: 10
            # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
            # 连接池名称
            pool-name: MyHikariCP
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            # 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 30000
    jpa: 
        properties: 
            hibernate:
                hbm2ddl:
                    auto: update
        show-sql: true
midcu:
    authsystem: 
        security:
            # 登录、注销、注册、swagger相关页面接口
            permitUrl: /login,/logout,/signup,/swagger-ui/**,/v3/api-docs/**,/captcha # 默认值 Null 无免认证路径
            tokenHeader: Authorization
            expirationTime: 86400000 # 1 day
            admin: false # 是否开启管理员账号
            user: ## 管理员账号
                username: admin
                password: '{bcrypt}$2a$10$JnpZPl3538rLRtfqR3xZzeXRkK9VQtm2TbizEhGhR6iqSK5ofFAiu' #vue-auth123456 的 bcrypt加密 且加上{bcrypt}前缀
